### ISSUE TITLE
Backface culling wipes out every other row in the triangle strip.

### ISSUE THREAD

**Issue by RichardHabeeb** [cis585spring2016/sobriquet#8]
I've tried adjusting the winding order in terrain. I cannot figure out why this is happening. Enable culling to see the problem.

**Comment by trentn** [comment]
I took a look. And I can't think of anything off the top of my head... but I do notice that it seems like it does every other 2 rows.

**Comment by trentn** [comment]
http://www.gamedev.net/topic/174403-left-hand-right-hand-problem-with-triangles/

The second response (the one from John Bolton) might lend some insight.

I think we are basically missing a triangle after every two rows, from how we did our indexing logic.
That would explain why a full two rows gets culled.

**Comment by trentn** [comment]
http://www.gamedev.net/topic/259017-drawing-height-map-using-triangle-strip-with-ccw-problem/

just another link explaining triangle lists winding orders...

**Comment by trentn** [comment]
Fixed. I will be pushing the new code to the branch.
